# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ScreenCapture
DESTDIR = ../bin
CONFIG += debug
LIBS += -L"$(SolutionDir)/lib" \
    -L"$(NOINHERIT)" \
    -lavcodec \
    -lavdevice \
    -lavfilter \
    -lavformat \
    -lavutil \
    -lpostproc \
    -lswresample \
    -lswscale
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(../../../Desktop/Screen Capture QT/ScreenCapture.pri)
